services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: emr-backend
    environment:
      DB_HOST: mysql1
      DB_PORT: 3306
      DB_PASSWORD: admin
      DB_NAME: emr_app_db
    ports:
      - "3002:3002"
    depends_on:
      - mysql1

  mysql1:
    image: mysql:8.0
    container_name: emr-db
    environment:
      - MYSQL_DATABASE=emr_app_db
      - MYSQL_PASSWORD=admin
      - MYSQL_ROOT_PASSWORD=admin
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql

  react-app:
    image: node:18
    container_name: emr-frontend
    working_dir: /code/frontend
    command: sh -c "npm ci && npm start"
    environment:
      - HOST=0.0.0.0
      - PORT=3000
      - WDS_SOCKET_PORT=0
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      # can point to the backend, if read in code later
      # - REACT_APP_API_BASE=http://localhost:3002
    ports:
      - "3000:3000"
    volumes:
      - ./:/code
      - /code/frontend/node_modules
    depends_on:
      - app

volumes:
  db:
    driver: local


# services:
#   app:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     container_name: emr-backend
#     environment:
#       DB_HOST: mysql1
#       DB_PORT: 3306
#       DB_PASSWORD: admin
#       DB_NAME: emr_app_db
#     ports:
#       - "3002:3002"
#     depends_on:
#       - mysql1
#     stdin_open: true
#     tty: true

#   mysql1:
#     image: mysql:8.0
#     container_name: emr-db
#     environment:
#       - MYSQL_DATABASE=emr_app_db
#       - MYSQL_PASSWORD=admin
#       - MYSQL_ROOT_PASSWORD=admin
#     ports:
#       - '3306:3306'
#     volumes:
#       - db:/var/lib/mysql
#     stdin_open: true
#     tty: true

#   react-app:
#     image: node:latest
#     container_name: emr-frontend
#     ports:
#       - "3000:3000"
#     command: ["bin/bash"]
#     volumes:
#       - ./:/code
#     depends_on:
#       - app
#     stdin_open: true
#     tty: true

# volumes:
#   db:
#     driver: local
    
