services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: emr-backend
    environment:
      DB_HOST: mysql1
      DB_PORT: 3306
      DB_PASSWORD: admin
      DB_NAME: emr_app_db
    ports:
      - "3002:3002"
    depends_on:
      - mysql1
    stdin_open: true
    tty: true

  mysql1:
    image: mysql:8.0
    container_name: emr-db
    environment:
      - MYSQL_DATABASE=emr_app_db
      - MYSQL_PASSWORD=admin
      - MYSQL_ROOT_PASSWORD=admin
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
    stdin_open: true
    tty: true

  react-app:
    image: node:latest
    container_name: emr-frontend
    ports:
      - "3000:3000"
    command: ["bin/bash"]
    volumes:
      - ./:/code
    depends_on:
      - app
    stdin_open: true
    tty: true

volumes:
  db:
    driver: local
    
