// backend/seedPatients.js

const DEFAULT_PATIENTS = [
  {
    lastname: 'Smith',
    firstname: 'John',
    preferredname: 'Johnny',
    address: '123 Main St',
    city: 'Toronto',
    postalcode: 'M1A 1A1',
    province: 'Ontario',
    homephone: '4161111111',
    workphone: '4162222222',
    cellphone: '4163333333',
    email: 'johnsmith@example.com',
    dob: '1980-05-15',
    sex: 'M',
    healthinsurance_number: 'A123456789',
    healthinsurance_version_code: 'AB',
    patient_status: 'active',
    family_physician: 'Dr. Wong'
  },
  {
    lastname: 'Smith',
    firstname: 'Anna',
    preferredname: 'Annie',
    address: '123 Main St',
    city: 'Toronto',
    postalcode: 'M1A 1A1',
    province: 'Ontario',
    homephone: '4161111111',
    workphone: '',
    cellphone: '4167777777',
    email: 'annasmith@example.com',
    dob: '1985-03-12',
    sex: 'F',
    healthinsurance_number: 'A123456790',
    healthinsurance_version_code: 'AC',
    patient_status: 'active',
    family_physician: 'Dr. Wong'
  },
  {
    lastname: 'Smith',
    firstname: 'Emily',
    preferredname: 'Em',
    address: '123 Main St',
    city: 'Toronto',
    postalcode: 'M1A 1A1',
    province: 'Ontario',
    homephone: '',
    workphone: '',
    cellphone: '4169990000',
    email: 'emilysmith@example.com',
    dob: '2010-07-04',
    sex: 'F',
    healthinsurance_number: 'A123456791',
    healthinsurance_version_code: 'AD',
    patient_status: 'active',
    family_physician: 'Dr. Wong'
  },
  {
    lastname: 'Patel',
    firstname: 'Meera',
    preferredname: 'Meera',
    address: '456 Queen St',
    city: 'Ottawa',
    postalcode: 'K1A 0B1',
    province: 'Ontario',
    homephone: '6134445555',
    workphone: '',
    cellphone: '6139998888',
    email: 'meerapatel@example.com',
    dob: '1990-10-30',
    sex: 'F',
    healthinsurance_number: 'B987654321',
    healthinsurance_version_code: 'XY',
    patient_status: 'not enrolled',
    family_physician: 'Dr. Chan'
  },
  {
    lastname: 'Patel',
    firstname: 'Ravi',
    preferredname: 'Ravi',
    address: '456 Queen St',
    city: 'Ottawa',
    postalcode: 'K1A 0B1',
    province: 'Ontario',
    homephone: '6134445555',
    workphone: '6131234567',
    cellphone: '6131112222',
    email: 'ravipatel@example.com',
    dob: '1988-08-08',
    sex: 'M',
    healthinsurance_number: 'B987654322',
    healthinsurance_version_code: 'XZ',
    patient_status: 'active',
    family_physician: 'Dr. Chan'
  },
  {
    lastname: 'Patel',
    firstname: 'Anaya',
    preferredname: 'Naya',
    address: '456 Queen St',
    city: 'Ottawa',
    postalcode: 'K1A 0B1',
    province: 'Ontario',
    homephone: '',
    workphone: '',
    cellphone: '6132223333',
    email: 'anayapatel@example.com',
    dob: '2015-01-01',
    sex: 'F',
    healthinsurance_number: 'B987654323',
    healthinsurance_version_code: 'XY',
    patient_status: 'active',
    family_physician: 'Dr. Chan'
  },
  {
    lastname: 'Chen',
    firstname: 'David',
    preferredname: 'Dave',
    address: '789 Bloor St',
    city: 'Mississauga',
    postalcode: 'L5A 1B2',
    province: 'Ontario',
    homephone: '9051234567',
    workphone: '9057654321',
    cellphone: '9051112222',
    email: 'dchen@example.com',
    dob: '1975-02-20',
    sex: 'M',
    healthinsurance_number: 'C555666777',
    healthinsurance_version_code: 'CD',
    patient_status: 'active',
    family_physician: 'Dr. Lee'
  },
  {
    lastname: 'Chen',
    firstname: 'Linda',
    preferredname: 'Lin',
    address: '789 Bloor St',
    city: 'Mississauga',
    postalcode: 'L5A 1B2',
    province: 'Ontario',
    homephone: '9051234567',
    workphone: '',
    cellphone: '9053334444',
    email: 'lchen@example.com',
    dob: '1978-12-12',
    sex: 'F',
    healthinsurance_number: 'C555666778',
    healthinsurance_version_code: 'CE',
    patient_status: 'active',
    family_physician: 'Dr. Lee'
  },
  {
    lastname: 'Chen',
    firstname: 'Brian',
    preferredname: 'Bri',
    address: '789 Bloor St',
    city: 'Mississauga',
    postalcode: 'L5A 1B2',
    province: 'Ontario',
    homephone: '',
    workphone: '',
    cellphone: '9055556666',
    email: 'bchen@example.com',
    dob: '2005-11-11',
    sex: 'M',
    healthinsurance_number: 'C555666779',
    healthinsurance_version_code: 'CF',
    patient_status: 'active',
    family_physician: 'Dr. Lee'
  },
  {
    lastname: 'Nguyen',
    firstname: 'Linh',
    preferredname: 'Linh',
    address: '123 Dundas St',
    city: 'Toronto',
    postalcode: 'M5G 1Z8',
    province: 'Ontario',
    homephone: '4168887777',
    workphone: '',
    cellphone: '4162224444',
    email: 'linhnguyen@example.com',
    dob: '1992-04-05',
    sex: 'F',
    healthinsurance_number: 'D123987654',
    healthinsurance_version_code: 'GH',
    patient_status: 'active',
    family_physician: 'Dr. Singh'
  },
  {
    lastname: 'Lee',
    firstname: 'Michael',
    preferredname: 'Mike',
    address: '55 King St',
    city: 'Toronto',
    postalcode: 'M5V 3C6',
    province: 'Ontario',
    homephone: '4166543210',
    workphone: '4161239876',
    cellphone: '4163334444',
    email: 'mlee@example.com',
    dob: '1983-06-10',
    sex: 'M',
    healthinsurance_number: 'E456789012',
    healthinsurance_version_code: 'IJ',
    patient_status: 'active',
    family_physician: 'Dr. Khan'
  },
  {
    lastname: 'Taylor',
    firstname: 'Sarah',
    preferredname: 'Sarah',
    address: '8 Front St',
    city: 'Toronto',
    postalcode: 'M5E 1B2',
    province: 'Ontario',
    homephone: '',
    workphone: '4167654321',
    cellphone: '4168765432',
    email: 'sarahtaylor@example.com',
    dob: '1995-08-25',
    sex: 'F',
    healthinsurance_number: 'F321654987',
    healthinsurance_version_code: 'KL',
    patient_status: 'not enrolled',
    family_physician: 'Dr. Khan'
  },
  {
    lastname: 'Ali',
    firstname: 'Zara',
    preferredname: 'Z',
    address: '99 Weston Rd',
    city: 'Toronto',
    postalcode: 'M9N 1Y4',
    province: 'Ontario',
    homephone: '',
    workphone: '',
    cellphone: '6472223333',
    email: 'zaraali@example.com',
    dob: '2002-09-14',
    sex: 'F',
    healthinsurance_number: 'G789456123',
    healthinsurance_version_code: 'MN',
    patient_status: 'active',
    family_physician: 'Dr. Khan'
  },
  {
    lastname: 'Brown',
    firstname: 'Daniel',
    preferredname: 'Dan',
    address: '456 Lakeshore Blvd',
    city: 'Toronto',
    postalcode: 'M8V 1C2',
    province: 'Ontario',
    homephone: '',
    workphone: '',
    cellphone: '6471111111',
    email: 'danbrown@example.com',
    dob: '1982-11-30',
    sex: 'M',
    healthinsurance_number: 'H321789654',
    healthinsurance_version_code: 'OP',
    patient_status: 'active',
    family_physician: 'Dr. Patel'
  },
  {
    lastname: 'Jones',
    firstname: 'Ashley',
    preferredname: 'Ash',
    address: '12 Park St',
    city: 'Hamilton',
    postalcode: 'L8P 4W7',
    province: 'Ontario',
    homephone: '',
    workphone: '',
    cellphone: '2891234567',
    email: 'ashjones@example.com',
    dob: '1999-02-02',
    sex: 'F',
    healthinsurance_number: 'I147258369',
    healthinsurance_version_code: 'QR',
    patient_status: 'active',
    family_physician: 'Dr. Chan'
  },
  {
    lastname: 'White',
    firstname: 'Noah',
    preferredname: 'Noah',
    address: '23 East Ave',
    city: 'Kingston',
    postalcode: 'K7L 2X5',
    province: 'Ontario',
    homephone: '',
    workphone: '',
    cellphone: '6131237890',
    email: 'nwhite@example.com',
    dob: '2000-12-01',
    sex: 'M',
    healthinsurance_number: 'J654789321',
    healthinsurance_version_code: 'ST',
    patient_status: 'not enrolled',
    family_physician: 'Dr. Chan'
  }
];

module.exports = DEFAULT_PATIENTS;
